services:
  - type: web
    name: rotc-system-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # You'll set this in Render dashboard
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        sync: false
    healthCheckPath: /api/health
    
  - type: web
    name: rotc-system-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://rotc-system-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
